"""Add test table

Revision ID: 6a0466b077c6
Revises: 0844460f7076
Create Date: 2024-01-17 09:54:39.293506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a0466b077c6'
down_revision: Union[str, None] = '0844460f7076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tests_migrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tests_migrations')
    # ### end Alembic commands ###
